name: hugging_face
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - tqdm
  - pip:
    - torch
    - transformers
    - accelerate
